language: python
sudo: required
services:
  - cassandra

env:
  matrix:
    - TOX_ENV=py27-django110
    - TOX_ENV=py36-django110
    - TOX_ENV=py27-django111
    - TOX_ENV=py36-django111
    - TOX_ENV=py36-django21
    - TOX_ENV=py36-djangomaster
  global:
    - CASS_DRIVER_NO_CYTHON=1
    - CASS_HOST=127.0.0.1

python:
  - "3.6"

addons:
  apt:
    packages:
    - build-essential
    - python-dev
    - pypy-dev
    - libev4
    - libev-dev

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
